export const UI_STRINGS = {
  "Dubhe Agent V1.7 — 网页端智能体": "Dubhe Agent V1.7 — Browser Agent",
  "正在加载 Dubhe Agent": "Loading Dubhe Agent",
  "V1.7 · 网页端智能体": "V1.7 · Browser Agent",
  "载入资源": "Resources",
  "加载模块": "Modules",
  "初始化内核": "Kernel",
  "挂载界面": "Interface",
  "正在初始化…": "Initializing…",
  "重新加载": "Reload",
  "注销 Service Worker、清空本站缓存后重新打开（不会删除会话与密钥）": "Unregister the service worker, clear this site's cache and reload. Conversations and keys are preserved.",
  "清缓存后重载": "Clear cache & reload",
  "沙箱在本地运行 · 密钥只存浏览器": "Local sandbox · Keys stay in your browser",
  "返回导航页": "Back to home",
  "收起侧栏": "Collapse sidebar",
  "模型": "Model",
  "从 GET /v1/models 刷新": "Refresh from GET /v1/models",
  "刷新模型列表": "Refresh models",
  "搜索模型…": "Search models…",
  "搜索模型": "Search models",
  "清空搜索": "Clear search",
  "清空": "Clear",
  "会话记录": "Conversations",
  "新建会话（当前已是空会话时直接复用，不会堆空记录）": "New conversation; reuses the current conversation if it is already empty.",
  "新建": "New",
  "一键清除所有会话记录（含各自的消息、检查点与沙箱文件），不可恢复": "Permanently delete all conversations, checkpoints and workspace files.",
  "直连模式": "Direct mode",
  "构建版本；若与最新改动不符，请强制刷新（Ctrl/Cmd + Shift + R）": "Build version. Hard-refresh with Ctrl/Cmd + Shift + R if it is outdated.",
  "点击查看 token 构成": "View token breakdown",
  "设置": "Settings",
  "导出会话 JSON": "Export conversation as JSON",
  "导出": "Export",
  "从 JSON 导入会话": "Import conversation from JSON",
  "导入": "Import",
  "展开侧栏": "Expand sidebar",
  "推理级别：Mini / Low / Medium / High / Max / Ultra。Claude→budget_tokens，GPT/Gemini/Grok→reasoning_effort，DeepSeek→reasoning，GLM→thinking；不支持的模型自动降级": "Reasoning: Mini / Low / Medium / High / Max / Ultra. Native provider parameters are used; unsupported models fall back automatically.",
  "思考": "Reasoning",
  "代码沙箱：开启后 Agent 可执行 JS/Python/C++ 代码（文件读写、生图、子智能体委派不受此开关影响）": "Enable JS/Python/C++ execution. File operations, image tools and delegation are independent of this switch.",
  "沙箱": "Sandbox",
  "未检测到本地中继时联网不可用": "Web tools require an available relay.",
  "联网": "Web",
  "TeamoRouter Fast mode（service_tier=fast，2x 计费，仅 GPT 系列）": "TeamoRouter Fast mode (service_tier=fast; 2× billing; GPT only)",
  "快速": "Fast",
  "沙箱面板：文件树 / 下载 / 清空": "Workspace: file tree / downloads / clear",
  "展开或收起沙箱面板": "Toggle workspace panel",
  "面板": "Panel",
  "定位到最新输出": "Jump to latest output",
  "最新输出": "Latest output",
  "撤销刚才的回滚": "Undo the last rollback",
  "⤺ 撤销回滚": "⤺ Undo rollback",
  "添加附件（图片 / 视频 / PDF / ZIP / 文本 / 代码；也可拖拽、粘贴文件或文件链接），或拍照": "Add images, videos, PDFs, ZIP, text or code; drag/paste files or file links, or take a photo.",
  "添加附件或拍照": "Add attachment or photo",
  "附件操作": "Attachment actions",
  "选择文件": "Choose files",
  "拍照并编辑后添加": "Take and edit a photo",
  "拍照": "Camera",
  "粘贴文件链接，经中继跨域拉取为附件": "Paste a file link to download through the relay.",
  "文件链接": "File link",
  "拍摄照片": "Take a photo",
  "消息输入框": "Message",
  "你出想法，Duhbe来实现": "Ideas in. Software out.",
  "输入消息，可粘贴或拖入附件…": "Ideas in. Software out.",
  "输入消息，Enter 发送 / Shift+Enter 换行，可拖入或粘贴附件…": "Ideas in. Software out.",
  "发送 (Enter)": "Send (Enter)",
  "发送": "Send",
  "内容由AI生成，请仔细甄别 ·": "AI-generated content. Verify important information ·",
  "文档与协议": "Docs & terms",
  "文件": "Files",
  "记忆": "Memory",
  "收起面板": "Collapse panel",
  "0 个文件": "0 files",
  "ZIP 打包后的估算体积（STORE 容器，图片已是压缩格式）": "Estimated ZIP size (STORE; images are already compressed)",
  "把沙箱内全部文件打包下载（.zip）": "Download all workspace files as ZIP",
  "清空沙箱文件": "Clear workspace files",
  "长效记忆": "Long-term memory",
  "跨会话 · 只展示 / 多选删除": "Across conversations · view / multi-select to delete",
  "删除选中的记忆": "Delete selected memories",
  "删除": "Delete",
  "关闭": "Close",
  "Key 以": "Keys start with",
  "开头，在": "; create one in the",
  "TeamoRouter 控制台": "TeamoRouter console",
  "创建。仅保存在本机浏览器 localStorage，随请求头直发网关，不经过任何第三方。": ". Stored only in this browser; sent directly to the gateway in request headers, not through us.",
  "保存": "Save",
  "关闭预览": "Close preview",
  "放大 (+)": "Zoom in (+)",
  "缩小 (−)": "Zoom out (−)",
  "重置 (0)": "Reset (0)",
  "跳到模型 / 文件…": "Jump to model / file…",
  "⌘K 命令 · Ctrl+1–9 切模型 · ⌘B 面板 · Esc 关闭": "⌘K commands · Ctrl+1–9 models · ⌘B panel · Esc close",
  "Token 构成": "Token breakdown",
  "账户": "Account",
  "仅保存在本机": "Stored on this device only",
  "自定义中继地址": "Custom relay URL",
  "留空自动探测": "Leave blank for auto-detection",
  "当前中继": "Current relay",
  "检测中…": "Checking…",
  "外观": "Appearance",
  "主题": "Theme",
  "浅色": "Light",
  "深色": "Dark",
  "字号": "Text size",
  "小": "Small",
  "中": "Medium",
  "大": "Large",
  "界面动效": "Animations",
  "跟随系统": "System",
  "开": "On",
  "关": "Off",
  "对话行为": "Conversation",
  "代码沙箱": "Code sandbox",
  "远程 C++（Compiler Explorer）": "Remote C++ (Compiler Explorer)",
  "代码会发送到 godbolt.org": "Source is sent to godbolt.org",
  "联网抓取（fetch_url）": "Web fetch (fetch_url)",
  "快速模式（Fast）": "Fast mode",
  "GPT 系列 · 2× 计费": "GPT models · 2× billing",
  "深度思考": "Deep reasoning",
  "思考强度": "Reasoning level",
  "执行预算": "Execution budget",
  "外部副作用上限 / 轮": "External actions / turn",
  "抓取 / 检索 / 生图 / 识图 / 委派等 · 下一轮生效": "Fetch / search / image / vision / delegation · next turn",
  "外部副作用上限": "External action limit",
  "工具调用上限 / 轮": "Tool calls / turn",
  "下一轮生效": "Applies next turn",
  "工具调用上限": "Tool call limit",
  "恢复默认": "Reset defaults",
  "多模态模型": "Media models",
  "生图模型": "Image generation model",
  "随会话保存": "Saved with this conversation",
  "识图模型": "Vision model",
  "识图 / PDF": "Images / PDF",
  "视频识别模型": "Video model",
  "仅 Gemini 系可收视频": "Video input requires a Gemini-compatible model",
  "灰区图片远程复核": "Remote image review",
  "本地拿不准时交 Gemini 3.5 Flash Lite 复核 · 每轮 ≤ 3 张": "Gemini 3.5 Flash Lite reviews uncertain local results · ≤ 3 images / turn",
  "关于": "About",
  "版本": "Version",
  "构建": "Build",
  "架构": "Architecture",
  "架构号 Dubhe Helix 3.0；DC（Dubhe Cambrian，天枢·寒武）只是产品代号": "Architecture: Dubhe Helix 3.0. DC (Dubhe Cambrian) is a product codename.",
  "中继": "Relay",
  "本地存储": "Local storage",
  "部署提交": "Deployment commit",
  "来自线上 build.json：这次部署对应的 git 提交与文件清单，可用 tools/verify-build.mjs 逐文件核对": "Deployment provenance from build.json. Verify every file with tools/verify-build.mjs.",
  "临时缓存": "Temporary cache",
  "不含会话、密钥、设置与记忆": "Excludes conversations, keys, settings and memory",
  "清除临时缓存": "Clear temporary cache",
  "清空当前会话": "Clear this conversation",
  "清空所有数据": "Clear all data",
  "完成": "Done",
  "语言": "Language",
  "跟随浏览器": "Browser default",
  "英文界面启用英文系统提示词；回复仍跟随用户语言": "English UI uses English system prompts; replies follow the user's language.",
  "分享": "Share",
  "分享对话": "Share conversation",
  "多选消息": "Select messages",
  "正文与附件": "Text & attachments",
  "包含工具详情": "Include tool details",
  "包含思考过程": "Include reasoning",
  "仅在本机导出。请确认所选消息与附件不含密钥或敏感信息。": "Exported locally. Check selected messages and attachments for keys or sensitive information.",
  "全选": "Select all",
  "全不选": "Select none",
  "长图 PNG": "Long image · PNG",
  "单页 HTML": "Single-page HTML",
  "取消": "Cancel",
  "正在导出…": "Exporting…",
  "语音输入": "Dictate",
  "停止语音输入": "Stop dictation",
  "原生语音输入不可用": "Native speech recognition is unavailable",
  "长任务完成通知": "Long-task notifications",
  "固定：超过60秒且在后台；手动停止不通知": "Fixed: over 60s and in the background; manual stops are excluded.",
  "开启通知": "Enable notifications",
  "关闭通知": "Disable notifications",
  "有帮助": "Helpful",
  "没有帮助": "Not helpful",
  "赞": "Helpful",
  "踩": "Not helpful",
  "评价可选，仅对上一条正常完成的答复；会作为下一轮模型参考": "Optional, for the latest completed answer only; used as context for the next model request.",
  "已标记有帮助": "Marked helpful",
  "已标记没有帮助": "Marked not helpful",
  "已取消评价": "Rating removed",
  "已复制": "Copied",
  "复制": "Copy",
  "复制失败：浏览器拒绝了剪贴板权限": "Copy failed: clipboard permission denied",
  "复制这条消息": "Copy this message",
  "复制本轮回复": "Copy this turn's reply",
  "回滚": "Roll back",
  "回滚到本轮之前（将移除该轮及其后的消息）": "Roll back before this turn (removes this and later turns)",
  "重新生成": "Regenerate",
  "重新生成并覆盖最近这一条回答（更早的回答请先「回滚」再重新提问）": "Regenerate the latest answer. Roll back first to regenerate an older turn.",
  "准备就绪": "Ready",
  "已就绪": "Ready",
  "就绪": "Ready",
  "闲置": "Idle",
  "连接中": "Connecting",
  "连接中…": "Connecting…",
  "正在连接…": "Connecting…",
  "思考中": "Thinking",
  "思考中…": "Thinking…",
  "输出中": "Responding",
  "生成中": "Generating",
  "生成中…": "Generating…",
  "执行中": "Executing",
  "执行中…": "Executing…",
  "审核中": "Reviewing",
  "审核中…": "Reviewing…",
  "已完成": "Completed",
  "已停止": "Stopped",
  "已停止生成": "Generation stopped",
  "错误": "Error",
  "失败": "Failed",
  "未知": "Unknown",
  "加载中…": "Loading…",
  "隐藏": "Hide",
  "展开": "Expand",
  "收起": "Collapse",
  "跳过": "Skip",
  "换一批": "Shuffle",
  "本地": "Local",
  "历史": "History",
  "不支持": "Not supported",
  "普通": "Standard",
  "详细": "Detailed",
  "未连接": "Disconnected",
  "已连接": "Connected",
  "未配置": "Not configured",
  "后续输出按发起顺序缓冲展示": "Later output is buffered in launch order",
  "纯文本": "Text only",
  "思考链已加密": "Reasoning is hidden by the provider",
  "当前浏览器不支持原生语音识别": "This browser does not support native speech recognition",
  "语音识别不会自动发送消息；音频由浏览器原生服务处理": "Dictation never sends automatically. Audio is processed by the browser's native speech service.",
  "使用浏览器原生语音识别，不经过应用中继": "Uses native browser speech recognition, not the app relay",
  "超出安全画布尺寸，请减少选择或改用HTML；没有截断任何消息": "Selection exceeds safe canvas limits. Select fewer messages or export HTML; no messages were truncated.",
  "HTML保留折叠、复制、图表缩放与图片预览，不包含应用设置或密钥": "HTML keeps folds, copying, chart zoom and image preview; no app settings or keys.",
  "还没有会话记录": "No conversations yet",
  "直连": "Direct",
  "直连 · .com": "Direct · .com",
  "直连 · .cn": "Direct · .cn",
  "Dubhe Agent · 基于": "Dubhe Agent · powered by",
  "网关的网页端智能体": "gateway · a browser agent",
  "模型自选 · 代码沙箱 · 对话回滚 · 工具调用循环": "Your model · code sandbox · rollback · real tool loops",
  "在此会话中创建或上传的所有文件都将保存在这里": "Files created or uploaded in this conversation appear here.",
  "拖入 / 粘贴附件，或让 Agent 在沙箱里生成": "Drop/paste attachments, or ask the Agent to create files.",
  "默认值": "Defaults",
  "Dubhe Helix 3.0 · DC（天枢·寒武）": "Dubhe Helix 3.0 · DC (Dubhe Cambrian)",
  "非 Pages 部署（无 build.json）": "Not a Pages deployment (no build.json)",
  "网页中继不可达：60 秒后自动重探；点顶栏「联网」可立即重试": "Relay unavailable. Retrying in 60 seconds; click Web to retry now.",
  "换一批任务示例": "Shuffle task suggestions",
  "连接模型中": "Connecting to model",
  "沙箱执行中": "Executing in sandbox",
  "出错": "Error",
  "停止": "Stop",
  "用户": "You",
  "思考过程": "Reasoning",
  "文档": "Docs",
  "更新日志": "Changelog",
  "用户协议": "User agreement",
  "服务条款": "Terms of service",
  "隐私政策": "Privacy policy",
  "文档 · Dubhe Agent V1.7": "Docs · Dubhe Agent V1.7",
  "返回首页": "Home",
  "当前环境不支持系统通知；iOS需添加到主屏幕后使用": "System notifications are unavailable here. On iOS, add this app to the Home Screen first.",
  "重命名会话": "Rename conversation",
  "删除会话": "Delete conversation",
  "早上好": "Good morning",
  "下午好": "Good afternoon",
  "晚上好": "Good evening",
  "下载": "Download",
  "沙箱中没有这个文件": "This file is missing from the workspace",
  "图片": "Image",
  "放大": "Zoom in",
  "缩小": "Zoom out",
  "复位": "Reset",
  "地图缩放": "Map zoom",
  "Dubhe Agent — 浏览器里的智能体": "Dubhe Agent — Your Browser Agent",
  "Web Agent · 约 48 秒": "Web Agent · about 48 seconds",
  "开始探索": "Explore",
  "播放介绍片": "Play introduction",
  "沙箱跑代码、工作区落盘、出图与思考档。片中随时可跳过。": "Real code execution, workspace files, images and reasoning. Skip any time.",
  "隔离沙箱": "Isolated sandbox",
  "文件带走": "Take your files",
  "思考七档": "Seven reasoning levels",
  "影片加载": "Loading introduction",
  "正在加载影片": "Loading the film",
  "开片": "Play",
  "跳过片头，直接看介绍": "Skip the film and explore",
  "暂停": "Pause",
  "开启声音": "Enable sound",
  "打开网页，即是工作台": "Open the page. Start building.",
  "三语沙箱": "Three-language sandbox",
  "120MB 持久化": "120MB persistent workspace",
  "生图与识图": "Image generation & vision",
  "七档思考": "Seven reasoning levels",
  "隔离执行": "Isolated execution",
  "JavaScript Worker、Pyodide、远程 C++。超时可杀，改动写回工作区。": "JavaScript Workers, Pyodide and remote C++. Terminable execution; file changes return to your workspace.",
  "3 个文件": "3 files",
  "本地工具": "Local tools",
  "正则、哈希、编解码、差分、JSON，不必为这些开沙箱。": "Regex, hashes, codecs, diffs and JSON—no code sandbox needed.",
  "ZIP 打包": "ZIP export",
  "压缩、解压。刷新后工作区还在。": "Archive and extract files. Your workspace survives refreshes.",
  "返回探索页": "Back to explore",
  "优势": "Why Dubhe",
  "能力": "Capabilities",
  "思考档": "Reasoning",
  "新特性": "What's new",
  "工作台": "Workbench",
  "流程": "Workflow",
  "原则": "Principles",
  "开始对话": "Start a conversation",
  "浏览器里的": "An agent.",
  "智能体。": "In your browser.",
  "在网页里写代码、管文件、出图、识图、深度思考。会话级沙箱就在侧栏，Key 只存在本机。打开即可开始，不必安装客户端。": "Write code, manage files, generate images and reason deeply in a browser. A per-conversation workspace lives in the sidebar; your key stays on your device. No desktop client required.",
  "进入对话": "Open the app",
  "了解能力": "Explore capabilities",
  "隔离沙箱，超时可杀": "Isolated, terminable execution",
  "会话工作区，刷新还在": "Persistent conversation workspace",
  "思考档七档可调": "Seven adjustable reasoning levels",
  "不经过我们的账号": "No account system from us",
  "少而准的工具，而不是仪表盘。": "Focused tools. Not another dashboard.",
  "模型只调用真实存在的能力：浏览器内的代码与文件、网关生图与识图、本地编解码。没有的功能不会假装有。": "The model calls real capabilities: browser code and files, gateway image tools and local utilities. Missing capabilities are disclosed, not simulated.",
  "JavaScript Worker、Pyodide（可装第三方库）与远程 C++20。沙箱断网：fetch / XHR / WebSocket 被拆除，Python 只放行装包的 CDN 与 PyPI；回写文件先过路径与容量校验，internal/ 受保护。超时可杀，stdout / 返回值可捕获。": "JavaScript Workers, persistent Pyodide and remote C++20. Native network APIs are removed; controlled GET is available only through an enabled relay. Python permits package/runtime CDNs. File paths and quotas are validated and internal files protected. Capture stdout/results and terminate execution.",
  "工作区": "Workspace",
  "读写、追加、局部替换、复制删除、正则搜索、文本差分、JSON 整理。ZIP 打包带走，容量 120 MB。": "Read/write, append, targeted replacement, copy/delete, regex search, diffs and JSON. Export everything as ZIP, with a 120MB workspace budget.",
  "图像": "Images",
  "文生图与改图走 generate_image；识图统一 analyze_image。对话通道保持纯文本，结果写入沙箱 outputs/。": "Generate/edit raster images with generate_image and inspect them with analyze_image. The conversation channel stays text-only; images are saved in outputs/.",
  "Off → Ultra 七档。过程可展开，耗时可见。Max 与 Ultra 才允许委派；Ultra 另加自检与多专家复核。": "Seven levels from Off to Ultra. Expand visible reasoning and inspect duration. Delegation requires Max/Ultra; Ultra adds self-checks and specialist cross-validation.",
  "本地工作台": "Local workbench",
  "带走结果": "Take your results",
  "侧栏按卡片列出容量与文件树。打包 ZIP、下载单文件。有本地中继时还能对真实 git 仓库操作。任务结束后会顺手清掉自己留下的临时文件——只删它自己创建的，交付物与上传原件一律保留，删了什么都能在回复下方展开核对。": "Inspect storage and files in the sidebar, download one file or a ZIP, and use real Git with the local relay. Temporary cleanup preserves uploads and deliverables; expand the record to inspect what was discarded.",
  "思考档不是装饰。": "Reasoning levels mean something.",
  "Off 不发思考参数。High 不能委派。Ultra 在 Max 之上再加自检与多专家交叉复核。Claude 5 / GPT / Gemini 常常只在服务端思考、不返回正文。": "Off sends no reasoning parameter. High does not enable delegation. Ultra adds checks beyond Max. Some providers reason server-side without returning visible reasoning text.",
  "档位": "Level",
  "Claude 预算": "Claude budget",
  "委派": "Delegation",
  "还多什么": "Additional behavior",
  "否": "No",
  "不发送思考字段": "No reasoning parameter",
  "最轻、最快": "Lightest and fastest",
  "默认": "Default",
  "是": "Yes",
  "可派子智能体": "Specialist delegation",
  "自检 · 多专家复核": "Self-checks · cross-validation",
  "V1.7 新在哪里。": "What's new in V1.7.",
  "这一版把三件「看得见」的事做完：照片工作台按站点风格重写、介绍片的脉冲对齐到真实鼓点、全站补齐进入与反馈动效；再把两件「看不见」的事做实：沙箱断网加固与五件新工具。": "A unified photo workbench, beat-synchronized introduction and interface motion, backed by stronger sandbox boundaries and focused local tools. Current builds also add bilingual UI, private sharing, dictation, task notifications and optional answer feedback.",
  "照片工作台": "Photo workbench",
  "裁剪、旋转、翻转、亮度 / 对比 / 饱和 / 色温 / 锐化 / 晕影，六档滤镜与一键自动增强，全部在浏览器里按 Canvas 实时预览。与对话页同一套字体、圆角、阴影与暗色模式。": "Crop, rotate, flip, adjust brightness/contrast/saturation/temperature/sharpness/vignette, apply filters and auto-enhance. Everything previews locally on Canvas, using the app's typography, surfaces and dark theme.",
  "鼓点同步的介绍片": "Beat-synchronized introduction",
  "用 onset 检测把 47 秒配乐的 71 个底鼓逐个标出来，脉冲、切镜与字幕跟真实鼓点走，而不是按固定 BPM 猜。音频也修好了：点「播放介绍片」就有声，不再静音。": "Detected drum onsets drive pulses, transitions and captions rather than an assumed fixed BPM. Playing the introduction enables its existing soundtrack.",
  "沙箱断网": "Sandbox network boundaries",
  "JS Worker 拆掉 fetch / XHR / WebSocket / importScripts / IndexedDB，postMessage 私有化防伪造结果；Python 的 fetch 只放行 Pyodide CDN 与 PyPI；日志 / 返回值 / 文件都有硬上限，回写走路径白名单。": "Workers remove native network and persistence primitives; transport references are private. Explicitly enabled controlled networking remains bounded. Python permits only runtime/package sources; logs, results and file writes have limits.",
  "关沙箱也能用的本地工具。": "Local tools work without a code sandbox.",
  "这些在浏览器里直接跑，不消耗网关、也不需要 Worker / Pyodide。写正则、对拍文本、整理 JSON 时优先用它们。": "These run directly in the browser, without the gateway or a code worker. Prefer them for regex, text comparison, JSON and structured data tasks.",
  "构建 .26 起本地小工具收成两把伞：": "Local utilities are organized under two umbrella tools:",
  "（文本统计 / 去重 / 排序 / 大小写 + 正则 + 哈希 + 编解码 + Unicode）与": "(text statistics, deduplication, sorting, case, regex, hashes, codecs and Unicode) and",
  "（kind=csv 预览 / 过滤 / 聚合，kind=date 日期差 / 加减 / 工作日，kind=units 单位换算，kind=qr 本地二维码 SVG，Version 1–20 与 python-qrcode 逐位一致）。工具表分两层下发：核心 12 个每轮必带，其余按消息、附件和近几轮用量按需挂载。": "(CSV preview/filter/aggregation, date arithmetic, unit conversion and QR SVG). A core tool set is always available; others are mounted according to intent, attachments and recent use.",
  "从一句话到可下载的产物。": "From an idea to a downloadable result.",
  "智能体在浏览器里循环调用工具，直到写出文件、跑通测试或生成图像。你可以随时打开侧栏工作区拿走结果。": "The agent iterates through real tools to write files, test code or generate images. Open the workspace to take your results.",
  "写下任务": "Describe the task",
  "空状态有 20–30 字的挑战示例。点一下填入完整提示词，附件会进沙箱 uploads/。": "Choose a challenging starter prompt or write your own. Approved attachments enter uploads/.",
  "工具在跑": "Watch tools run",
  "芯片无边框、可复制入参。思考与调用都记下耗时。并行互不依赖的步骤会同一轮发出。": "Tool records keep command, stdout and optional stderr windows with individual copying. Independent tasks run concurrently; presentation follows launch order.",
  "核对结果": "Verify the result",
  "代码在沙箱执行，不是口算。长输出写入文件，识图返回全文而不是摘要。": "Code is actually executed. Long output can be saved to files; vision tools return complete text, not invented summaries.",
  "带走文件": "Take the files",
  "工作区按卡片呈现容量与树。打包 ZIP，刷新不丢。Key 与会话都在本机。": "Inspect the file tree and storage, export ZIPs and keep your workspace across refreshes. Keys and history stay local.",
  "为什么选我们？": "Why choose Dubhe?",
  "不是更大的仪表盘，而是浏览器里就能交差的智能体：工具真跑、文件能带走、没有的能力不会装有。": "An agent that can deliver from a browser: real tools, portable files and clear capability limits.",
  "打开即用": "Open and use",
  "没有客户端、没有账号墙。填入自己的 TeamoRouter Key，选模型就能开始。会话、附件、沙箱都在这一个标签页里。": "No client install or account wall. Add your own TeamoRouter key and choose a model. Conversations, attachments and files live in one tab.",
  "本地密钥": "Local keys",
  "密钥只写在本机浏览器，请求直发网关。我们不提供账号系统，也就没有「把你的对话存在我们服务器」这一环。": "Keys are stored only in your browser; model requests go to the gateway. We have no account backend that stores your conversations.",
  "工具会真跑": "Real execution",
  "JS / Python / C++ 在沙箱执行，超时可杀。工作区 120 MB，ZIP 打包带走。生图、识图、本地编解码都是真实调用，不是聊天窗里口算。": "Execute code through real runtimes, export a 120MB workspace and use genuine image and local data tools—not fabricated execution in a chat bubble.",
  "不装有的能力": "Honest capability boundaries",
  "没有模型原生网页搜索就写没有。识图走专用工具，git 只在本地中继。介绍页和对话页说同一份产品，方便核对。": "Web search is a health-declared relay tool, not a native model field. Vision uses dedicated tools; real Git requires a local relay, while a limited browser simulator works offline.",
  "不会假装有的能力。": "What we will not pretend to support.",
  "介绍页和对话页说的是同一份产品。下面这些限制写进提示词，模型不会用「已经搜过」来搪塞。": "These boundaries are also in the system prompt. Real results are required before claims of search, execution or browser verification.",
  "没有模型原生网页搜索。有本地中继时用 fetch_url 抓具体网址；GitHub Pages 上该开关不可用。": "No native model search. Concrete fetch/search/crawl tools require an enabled relay and declared capabilities; static Pages alone supplies none.",
  "对话模型看不见图片。识图必须走 analyze_image（deepseek-v4-flash-vision-exp），返回全文。": "The text model cannot see images. Use analyze_image with the configured vision model for complete analysis.",
  "run_git 只在本机工作区白名单命令下执行，不经 shell。没有中继就没有真实 git。": "Real Git uses the local relay's allowed workspace/commands, not arbitrary shell. Without it, only the limited browser simulator is available.",
  "Key 存在哪里？": "Where is my key stored?",
  "TeamoRouter 的 API Key 只写在本机浏览器。我们不提供账号系统，刷新后对话、附件与沙箱仍在 localStorage / 会话存储里。": "Your TeamoRouter key stays in browser storage. History, attachments and workspace persist locally; we do not operate an account database.",
  "和对话页是不是两套产品？": "Is the introduction a different product?",
  "不是。介绍页只负责说明，对话在 app.html。沙箱、工作区、生图、思考档、本地工具与这里写的一致。": "No. This page explains the same app available at app.html, with the same real tools and limitations.",
  "为什么有些模型不能识图？": "Why are images handled by a separate tool?",
  "对话通道一律纯文本，避免各模型 multimodal 行为不一致。需要看图时由工具调用专用识图模型，结果落盘后可以再读。": "Conversation stays text-only for consistent protocols. Dedicated vision tools inspect images and save results for later reading.",
  "现在就开始": "Start now",
  "打开对话页，填入 Key，选一个模型。空状态的示例点一下就是完整任务。": "Open the app, add your key and choose a model—or click a starter task.",
  "打开 Dubhe Agent": "Open Dubhe Agent",
  "GitHub 仓库": "GitHub repository",
  "对话": "Chat",
  "自动路由": "Auto routing",
  "热门": "Popular",
  "低价": "Low cost",
  "未检测到中继（网页抓取工具将被禁用）": "No relay detected (web fetch tools disabled)",
  "不发送思考参数": "No reasoning parameter",
  "极速浅层思考": "Fastest, shallow reasoning",
  "轻量快速思考": "Lightweight, quick reasoning",
  "默认均衡思考": "Balanced reasoning",
  "深度推理": "Deep reasoning",
  "深度推理 · 可委派子智能体": "Deep reasoning · delegation enabled",
  "极限深度 · 自检与多专家复核": "Maximum depth · checks and specialist review",
  "全屏查看图表": "View chart fullscreen",
  "正在启动 JS Worker…": "Starting JS Worker…",
  "JS Worker 已就绪，执行中…": "JS Worker ready; executing…",
  "用户反馈": "User feedback",
  "代码工具": "Code tools",
  "网页工具": "Web tools",
  "已安装": "Installed",
  "正则、哈希、编解码、Unicode、差分、JSON，再加 CSV、日期、文本整理、单位换算与二维码——共 33 件工具，常用本地处理不必开代码沙箱。关沙箱时代码执行不可用，文件工具仍在。": "Regex, hashes, codecs, Unicode, diffs, JSON, CSV, dates, text, units and QR codes. There are 33 registered tools; common local operations need no code sandbox. Disabling code execution leaves file tools available.",
  "浏览器里的智能体": "An agent in your browser",
  "沙箱隔离执行": "Isolated code execution",
  "工作区 120 MB": "120MB workspace",
  "出图与识图": "Generation & vision",
  "思考档 Off → Ultra": "Reasoning: Off → Ultra",
  "跑起来，结果落盘": "Run it. Save the result.",
  "差分 · 搜索 · JSON": "Diff · search · JSON",
  "ZIP 打包带走": "Take your files as ZIP",
  "首页": "Home",
  "打开对话": "Open the app",
  "更新日志与协议。": "Changelog & agreements.",
  "查看 V1.7 Stable 的重点更新、历史版本概览，以及使用本应用前应了解的协议与隐私约定。": "Explore current updates, historical releases and the terms/privacy information you should understand before using the app.",
  "独立项目声明：": "Independent project:",
  "Dubhe Agent 是独立开发的开源前端应用，与": "Dubhe Agent is an independently developed, open-source frontend. It and",
  "及其运营方": "its operator",
  "互不隶属": "are unaffiliated",
  "，不存在授权、合作、代理或背书关系。TeamoRouter 仅是本应用默认兼容的第三方模型网关之一（你也可以自行更换中继）；「TeamoRouter」名称与标识归其权利人所有，在本应用中仅作兼容性说明之用。": ". There is no authorization, partnership, agency or endorsement relationship. TeamoRouter is a compatible third-party model gateway; its name and marks belong to their owners and identify compatibility only."
};
